version: '3'

services:
  warehouse_api:
    build: .
    container_name: warehouse_api
    env_file:
      - .env
    command: bash -c 'python3 main.py'
    volumes:
      - .:/home/user/warehouse_api
    restart: always
    ports:
      - '8000:8000'
    expose:
      - 8000
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - ./postgres/data/db:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
